contact_links:
  - name: ðŸ’¬ General Questions & Discussion
    url: https://github.com/orgs/LostMinionsGames/discussions
    about: Ask questions, propose ideas, or start an open conversation about any Lost Minions Games project.